#!/usr/bin/env bash
set -e
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
ROOT_DIR=$( cd -- "$( dirname -- "${SCRIPT_DIR}" )" &> /dev/null && pwd )

echo "Formatting code with ruff"
ruff check --fix ./src
ruff format ./src
ruff check --fix ./tests
ruff format ./tests

echo "Type checking with mypy"
mypy ./src

rm -rf test/examples/TestResults*
(
  cd tests
  pytest .
)

echo "Making docs"
rm -rf test/examples/TestResults*
(
  cd docs
  make clean
  make html
)
