#!/usr/bin/env bash
set -e
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
ROOT_DIR=$( cd -- "$( dirname -- "${SCRIPT_DIR}" )" &> /dev/null && pwd )

cd ${ROOT_DIR}

echo "Formatting imports with isort"
isort ./src
isort ./plugins

echo "Formatting code with black"
black ./src
black ./plugins

echo "Linting with flake8"
flake8 ./src
flake8 ./plugins

echo "Type checking with mypy"
mypy ./src

(
  cd src/_nvtest/tests
  pytest .
)

echo "Making docs"
(
  cd docs
  make clean
  make html
)
