ARG BASE_IMAGE=pbspro/pbspro:latest
FROM ${BASE_IMAGE}

LABEL org.opencontainers.image.title="canary-pbs"
LABEL org.opencontainers.image.description="Canary CI base image for PBS tests"
LABEL org.opencontainers.image.source="https://github.com/sandialabs/canary"
