# Copyright NTESS. See COPYRIGHT file for details.
#
# SPDX-License-Identifier: MIT

"""Implements the ``canary gc`` subcommand for garbage-collecting successful test output files."""

import argparse
from typing import TYPE_CHECKING

from ..hookspec import hookimpl
from ..workspace import Workspace
from .base import CanarySubcommand

if TYPE_CHECKING:
    from ..config.argparsing import Parser


@hookimpl
def canary_addcommand(parser: "Parser") -> None:
    parser.add_command(GarbageCollect())


class GarbageCollect(CanarySubcommand):
    """Remove output files generated by jobs with a ``success`` status to free disk space."""

    name = "gc"
    description = "Garbage collect (remove) files generated by cases with status 'success'"

    def setup_parser(self, parser: "Parser") -> None:
        """Register the ``--dryrun`` flag to preview deletions without performing them."""
        parser.add_argument(
            "--dryrun",
            action="store_true",
            help="Show what would be removed by garbage collection, but don't perform deletion",
        )

    def execute(self, args: argparse.Namespace) -> int:
        """Run garbage collection on the current workspace, respecting ``--dryrun``."""
        workspace = Workspace.load()
        workspace.gc(dryrun=args.dryrun)
        return 0
