# Copyright NTESS. See COPYRIGHT file for details.
#
# SPDX-License-Identifier: MIT

# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import re
import sys
from pathlib import Path

import canary

docs_source_dir = os.path.dirname(__file__)

os.environ["CANARY_MAKE_DOCS"] = "1"

# Add doc/lib/python to sys.path for custom Sphinx extensions
sys.path.insert(0, str(Path(__file__).parent / "lib/python"))

# -- Project information -----------------------------------------------------

project = "canary"
copyright = "2024, National Technology & Engineering Solutions of Sandia, LLC (NTESS)"
author = "National Technology & Engineering Solutions of Sandia, LLC (NTESS)"

# The short X.Y version
version = re.sub(r"\+.*$", r"", canary.version)

# The full version, including alpha/beta/rc tags
release = canary.version


# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    "sphinx.ext.todo",
    "sphinx.ext.autodoc",
    "sphinx.ext.mathjax",
    "sphinx.ext.napoleon",
    "sphinx_design",
    "sphinxext.docrun",
    "sphinxext.imagesvg",
]
autodoc_member_order = "bysource"
autodoc_default_options = {"ignore-module-all": True}
autodoc_mock_imports = ["flux"]
autodoc_typehints_format = "fully-qualified"
python_use_unqualified_type_names = False
autodoc_type_aliases = {"type": "builtins.type"}

# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]
add_module_names = False
napoleon_numpy_docstring = False

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = "python"

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = [
    "tutorial/intro.how.rst",
    "tutorial/intro.pyt.rst",
    "tutorial/intro.testcase.rst",
    "tutorial/intro.testfile.rst",
    "tutorial/intro.why.rst",
    "tutorial/resource.spec.rst",
]


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = "pydata_sphinx_theme"
html_logo = "static/Canary_icon3_color_800.svg"

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = []

html_sidebars = {"index": ["search-button-field"], "**": ["search-button-field", "sidebar-nav-bs"]}

html_theme_options = {
    "navigation_depth": 4,
    "show_toc_level": 1,
    "github_url": "https://github.com/sandialabs/canary",
    "navbar_start": ["navbar-logo"],
    "navbar_end": ["theme-switcher", "navbar-icon-links"],
    "logo": {"text": f"canary {version}"},
    "navbar_persistent": [],
    "secondary_sidebar_items": ["page-toc"],
}

# -- Extension configuration -------------------------------------------------

# -- Options for todo extension ----------------------------------------------

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = True

# Set an environment variable so that colify will print output like it would to
# a terminal.
os.environ["COLIFY_SIZE"] = "25x120"
os.environ["COLUMNS"] = "120"

# Set a fixed width for argparse writer to ensure consistent documentation
# generation regardless of terminal size
os.environ["ARGPARSE_WRITER_WIDTH"] = "120"


def extract_changelog_synopsis(text: str) -> str:
    """Extract the top-level Synopsis section from a monthly changelog."""
    lines = text.splitlines()

    start = None

    for i in range(len(lines) - 1):
        heading = lines[i].strip()
        underline = lines[i + 1].strip()

        if heading == "Synopsis" and underline and set(underline) == {"-"}:
            start = i + 2
            break

    if start is None:
        return ""

    end = len(lines)

    for i in range(start, len(lines) - 1):
        heading = lines[i].strip()
        underline = lines[i + 1].strip()

        if heading and underline and set(underline) == {"-"}:
            end = i
            break

    return "\n".join(lines[start:end]).strip()


def ensure_changelog_history() -> None:
    """Ensure the changelog history page is generated.

    Generates docs/source/changelogs/history.rst if it does not exist, or if
    CANARY_DOCS_REGENERATE_CHANGELOG_HISTORY is set.
    """
    changelog_dir = Path(docs_source_dir) / "changelogs"
    history_file = changelog_dir / "history.rst"

    regenerate = os.getenv("CANARY_DOCS_REGENERATE_CHANGELOG_HISTORY") is not None

    if history_file.exists() and not regenerate:
        return

    changelog_dir.mkdir(parents=True, exist_ok=True)

    changelog_re = re.compile(r"changelog-(\d{4}-\d{2})\.rst$")

    changelogs = []

    for path in changelog_dir.glob("changelog-????-??.rst"):
        match = changelog_re.match(path.name)
        if not match:
            continue

        month = match.group(1)
        text = path.read_text(encoding="utf-8")
        synopsis = extract_changelog_synopsis(text)

        if not synopsis:
            synopsis = "No synopsis found."

        changelogs.append((month, path.stem, synopsis))

    changelogs.sort(reverse=True)

    lines = ["Changelog history", "=================", ""]

    if not changelogs:
        lines.extend(["No monthly changelogs are available.", ""])
    else:
        for month, docname, synopsis in changelogs:
            lines.extend(
                [
                    month,
                    "-" * len(month),
                    "",
                    synopsis,
                    "",
                    f":doc:`Full changelog <{docname}>`",
                    "",
                ]
            )

    print(f"Generating changelog history in {history_file}")
    history_file.write_text("\n".join(lines), encoding="utf-8")


def ensure_command_reference() -> None:
    """Ensure command reference documentation is generated.

    Generates command reference pages if they don't exist, or if
    CANARY_DOCS_REGENERATE_COMMANDS is set.
    """
    from _canary.subcommands import make_commands_docs

    user_dir = Path(docs_source_dir) / "user"
    command_dir = user_dir / "commands"

    # Check if we should regenerate
    regenerate = os.getenv("CANARY_DOCS_REGENERATE_COMMANDS") is not None

    # Check if command reference exists
    command_ref_exists = command_dir.exists() and (command_dir / "index.rst").exists()

    # Regenerate if needed
    if regenerate or not command_ref_exists:
        # Ensure directory exists
        command_dir.mkdir(parents=True, exist_ok=True)

        # Run command generation
        make_commands_docs(prefix=str(user_dir))


def ensure_pyt_directives() -> None:
    from canary_pyt import make_directives_docs

    user_dir = Path(docs_source_dir) / "user"
    directive_dir = user_dir / "directives"

    # Check if we should regenerate
    regenerate = os.getenv("CANARY_DOCS_REGENERATE_DIRECTIVES") is not None

    # Check if directive reference exists
    directive_ref_exists = directive_dir.exists() and (directive_dir / "index.rst").exists()

    # Regenerate if needed
    if regenerate or not directive_ref_exists:
        # Ensure directory exists
        directive_dir.mkdir(parents=True, exist_ok=True)

        # Run command generation
        make_directives_docs(prefix=str(user_dir))


def ensure_api_docs() -> None:
    from make_api_docs import make_api_docs

    api_docs_dir = Path(docs_source_dir) / "api-docs"

    # Check if we should regenerate
    regenerate = os.getenv("CANARY_DOCS_REGENERATE_API_DOCS") is not None

    # Check if api reference exists
    api_ref_exists = api_docs_dir.exists() and (api_docs_dir / "index.rst").exists()

    # Regenerate if needed
    if regenerate or not api_ref_exists:
        make_api_docs(prefix=docs_source_dir)


def ensure_rst_headings() -> None:
    from fix_rst_heading import fix_roots

    fix_roots([Path(docs_source_dir)])


# Ensure generated documentation is available
ensure_command_reference()
ensure_pyt_directives()
ensure_api_docs()
ensure_rst_headings()
# ensure_changelog_history()
