#!/usr/bin/env bash
set -e
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
ROOT_DIR=$( cd -- "$( dirname -- "${SCRIPT_DIR}" )" &> /dev/null && pwd )

cd ${ROOT_DIR}

echo "Formatting code with ruff"
ruff ./src
ruff ./plugins

echo "Type checking with mypy"
mypy ./src

(
  cd src/_nvtest/tests
  pytest .
)

echo "Making docs"
(
  cd docs
  make clean
  make html
)
