#!/usr/bin/env bash
set -e
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
ROOT_DIR=$( cd -- "$( dirname -- "${SCRIPT_DIR}" )" &> /dev/null && pwd )

echo "Formatting code with ruff"
ruff check --fix ./src
ruff format ./src

echo "Type checking with mypy"
mypy ./src

(
  cd src/_nvtest/tests
  pytest .
)

echo "Making docs"
(
  cd docs
  make clean
  make html
)
