#!/usr/bin/env python3
import argparse
import sys

def add(a: int, b: int) -> int:
    return a + b

def main():
    p = argparse.ArgumentParser(description="Add two numbers a and b")
    p.add_argument("a", type=int)
    p.add_argument("b", type=int)
    args = p.parse_args()
    print(add(args.a, args.b))
    return 0


if __name__ == "__main__":
    sys.exit(main())
